apiVersion: v1
baseDomain: cheap-aschips.co.uk
compute:
- hyperthreading: Enabled
  name: worker
  platform: 
    aws:
      type: t3.medium
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m4.large
  replicas: 3
metadata:
  creationTimestamp: null
  name: test-ag
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: eu-west-2
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FnbGVubjM2MDFsZHV3ZnNydDBmanl5aXd2b3p6dWhmOGxndDo4M0pRU0ZCVjQ1SFlaRVhaQVlTUzNONlc3NjJUTVlXQUNaM1FQNFIzQU5EUU5RNlZFUEs4RFE4UDlMVVFSVVJW","email":"aglenn@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FnbGVubjM2MDFsZHV3ZnNydDBmanl5aXd2b3p6dWhmOGxndDo4M0pRU0ZCVjQ1SFlaRVhaQVlTUzNONlc3NjJUTVlXQUNaM1FQNFIzQU5EUU5RNlZFUEs4RFE4UDlMVVFSVVJW","email":"aglenn@redhat.com"},"registry.connect.redhat.com":{"auth":"NTI1MTAzNTl8dWhjLTFMRFV3ZnNyVDBGSnl5SXdWb1p6dWhmOExndDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJaakkyT0RRNE5HUTJNVGMwTWprMU9XVXdNalZpTlRjd1pqZzVNbVUyTVNKOS5mRHk2NjN0cU1KaFJfRU4yNVJCUE9RS3g3SDg0ZHJ0NG9VdEl3eVpUbjNNNExiZmtEYkNZeXRtZjh0OTlvdERLaFdjazlZeXRGYVRzYmc4ZTRCNnFwOWRwVG04cHpvQm1yaTZkNy1QMGlDWHVOa2QyOE11aFQySUQ2QXdSR20tQVppeklLZUQ3WlpaLURjNjJGR29Odjd3SHBWdE9tbmRBd0E1ekp4SG9sRXdWYjBPRE1kOTNFakZPaG5hTVBheUlRS0RfY3poazlWb1JEWUhWYTNWSlphdkx5NkxlS0xNMHZPNGI0d0FfM2VHOXlCVnBNclM2b0VRS21jZ3E3S21Xc0Z6Wlo3cE9KZ0k1ajJYTWVGdGphRFpjTDktTVJCZFBvTjlCYlRRY3VuRlZ1aHJ5TWY2LUUtOXdMUTFIWGJGY1dvNkxBdHlKUTlydGxHaV9MYjRkLVc3bXZidHAxYm9vNzMyd3hDRDhGZS1naUhOU3JzdDllZmpfQVhNSjN2ZllVLUg1T1JYWGdJXzRoSjBWX2ZzdWJLNFBSX3Z0TU81cU5tbVFJdllQQXEtWVBKUEx4bEdoSFJwZ29sMFVhVndyRVB6OVkyME9ZVmR4dVpvbmx0YmhmbnNqOUpfenU4eUNXMzBBSnMxT2JGbjJZenlmMlp1S19nck9rdVNjQ2dYWnNVUEloaU5kMjUyN1VxMThRVVczNGM4WWhwenNCTzVLNExsV0tMSEp4TVdEZi1fMDFCRXJKLTgxZ1lIUTFqaE1pRWF3cFJadWE3cG05V05wWFpsZ1owdkV2Nlk0clk5MTNod09xb2h4RFZPUFR2eHFraUdWelRGNlU2QVVXX2xXR21KU1FoOEVQTURBRUJORFlBNEQ3MTFDWHZpSFczZkpQN2F2a2V2ZWpRVQ==","email":"aglenn@redhat.com"},"registry.redhat.io":{"auth":"NTI1MTAzNTl8dWhjLTFMRFV3ZnNyVDBGSnl5SXdWb1p6dWhmOExndDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJaakkyT0RRNE5HUTJNVGMwTWprMU9XVXdNalZpTlRjd1pqZzVNbVUyTVNKOS5mRHk2NjN0cU1KaFJfRU4yNVJCUE9RS3g3SDg0ZHJ0NG9VdEl3eVpUbjNNNExiZmtEYkNZeXRtZjh0OTlvdERLaFdjazlZeXRGYVRzYmc4ZTRCNnFwOWRwVG04cHpvQm1yaTZkNy1QMGlDWHVOa2QyOE11aFQySUQ2QXdSR20tQVppeklLZUQ3WlpaLURjNjJGR29Odjd3SHBWdE9tbmRBd0E1ekp4SG9sRXdWYjBPRE1kOTNFakZPaG5hTVBheUlRS0RfY3poazlWb1JEWUhWYTNWSlphdkx5NkxlS0xNMHZPNGI0d0FfM2VHOXlCVnBNclM2b0VRS21jZ3E3S21Xc0Z6Wlo3cE9KZ0k1ajJYTWVGdGphRFpjTDktTVJCZFBvTjlCYlRRY3VuRlZ1aHJ5TWY2LUUtOXdMUTFIWGJGY1dvNkxBdHlKUTlydGxHaV9MYjRkLVc3bXZidHAxYm9vNzMyd3hDRDhGZS1naUhOU3JzdDllZmpfQVhNSjN2ZllVLUg1T1JYWGdJXzRoSjBWX2ZzdWJLNFBSX3Z0TU81cU5tbVFJdllQQXEtWVBKUEx4bEdoSFJwZ29sMFVhVndyRVB6OVkyME9ZVmR4dVpvbmx0YmhmbnNqOUpfenU4eUNXMzBBSnMxT2JGbjJZenlmMlp1S19nck9rdVNjQ2dYWnNVUEloaU5kMjUyN1VxMThRVVczNGM4WWhwenNCTzVLNExsV0tMSEp4TVdEZi1fMDFCRXJKLTgxZ1lIUTFqaE1pRWF3cFJadWE3cG05V05wWFpsZ1owdkV2Nlk0clk5MTNod09xb2h4RFZPUFR2eHFraUdWelRGNlU2QVVXX2xXR21KU1FoOEVQTURBRUJORFlBNEQ3MTFDWHZpSFczZkpQN2F2a2V2ZWpRVQ==","email":"aglenn@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUIvhZDoFoKGhOsQPg+EBya/CPHiCKTNHlNggu0UQyKm3kQ04mpRCKmoM+mIn/DnR0wguMbYXP1vITPghkL5DUy/yr/NrLAPc1dImyyxcJtJYESfCALhj59GEMg9aoHQZot2+eRBeGBmwP+CyfwZ4FVsuTcOy7AvvVHZmqVxE6t5MoeQ5twH5SRlmYnWEsHvjH5ivoJ2ZHCKsljr5sTTLEhsZeRp5vvk4Aw3zXK9WvuCxcUNCbGgP4diawnEHeF4CTtKBB51F96yp15YiR+vldnQ5AyO7jftg5bBfrQ2F0mSE//4EA+/qAcx3DXi+e1ShBdOqJc1Tp6jx+7MWT7wVT aglenn@MacBook-Pro
