apiVersion: v1
kind: List
items:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    name: cluster
  spec:
    identityProviders:
      - mappingMethod: claim
        name: AzureAD
        openID:
          claims:
            email:
            - custom_email_claim
            - email
            name:
            - name
            preferredUsername:
            - email
            - preferred_username
          clientID: bd4e1cf1-8f75-4eec-bb40-fe95d554ee8c
          clientSecret:
            name: openid-client-secret
          extraAuthorizeParameters:
            include_granted_scopes: 'true'
          extraScopes:
            - email
            - profile
          issuer: >-
            https://login.microsoftonline.com/de84e170-138e-495c-aa45-01a8c241aa52/v2.0
        type: OpenID
      - name: ClusterAccount 
        mappingMethod: claim 
        type: HTPasswd
        htpasswd:
          fileData:
            name: openid-htpasswd
- kind: Secret
  apiVersion: v1
  metadata:
    name: openid-client-secret
    namespace: openshift-config
  data:
    clientSecret: ZTdmNkJwTVpyMUNBcHhWcllIWjI0bXd0ZmRlRzlkCg==
  type: Opaque
- kind: Secret
  apiVersion: v1
  metadata:
    name: openid-htpasswd
    namespace: openshift-config
  data:
    htpasswd: b3BzaGFkbTokMnkkMDUkNkxILks3REZvWUJ1cndoOUszQmNYT0NtTzZqNWVDSU42U2tYNkZOejBQNGEueTY3TzZIbmUK