apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  generation: 1
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: CLUSTER_NAME-infra-REGION1
spec:
  replicas: 1    
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
      machine.openshift.io/cluster-api-machineset: CLUSTER_NAME-infra-REGION1
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: CLUSTER_NAME-infra-REGION1
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          infra: infra         
        creationTimestamp: null
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/CLUSTER_NAME-rg/providers/Microsoft.Compute/images/CLUSTER_NAME
            sku: ""
            version: ""
          internalLoadBalancer: ""
          kind: AzureMachineProviderSpec
          location: REGION
          managedIdentity: CLUSTER_NAME-identity
          metadata:
            creationTimestamp: null
          natRule: null
          networkResourceGroup: ""
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: ""
          resourceGroup: CLUSTER_NAME-rg
          sshPrivateKey: ""
          sshPublicKey: ""
          subnet: CLUSTER_NAME-worker-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D2s_v3
          vnet: CLUSTER_NAME-vnet
          zone: "1"

apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  generation: 1
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: CLUSTER_NAME-infra-REGION2
spec:
  replicas: 1    
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
      machine.openshift.io/cluster-api-machineset: CLUSTER_NAME-infra-REGION2
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: CLUSTER_NAME-infra-REGION2
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          infra: infra         
        creationTimestamp: null
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/CLUSTER_NAME-rg/providers/Microsoft.Compute/images/CLUSTER_NAME
            sku: ""
            version: ""
          internalLoadBalancer: ""
          kind: AzureMachineProviderSpec
          location: REGION
          managedIdentity: CLUSTER_NAME-identity
          metadata:
            creationTimestamp: null
          natRule: null
          networkResourceGroup: ""
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: ""
          resourceGroup: CLUSTER_NAME-rg
          sshPrivateKey: ""
          sshPublicKey: ""
          subnet: CLUSTER_NAME-worker-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D2s_v3
          vnet: CLUSTER_NAME-vnet
          zone: "2"

apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  generation: 1
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: CLUSTER_NAME-infra-REGION3
spec:
  replicas: 1    
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
      machine.openshift.io/cluster-api-machineset: CLUSTER_NAME-infra-REGION3
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTER_NAME
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: CLUSTER_NAME-infra-REGION3
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          infra: infra         
        creationTimestamp: null
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/CLUSTER_NAME-rg/providers/Microsoft.Compute/images/CLUSTER_NAME
            sku: ""
            version: ""
          internalLoadBalancer: ""
          kind: AzureMachineProviderSpec
          location: REGION
          managedIdentity: CLUSTER_NAME-identity
          metadata:
            creationTimestamp: null
          natRule: null
          networkResourceGroup: ""
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: ""
          resourceGroup: CLUSTER_NAME-rg
          sshPrivateKey: ""
          sshPublicKey: ""
          subnet: CLUSTER_NAME-worker-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D2s_v3
          vnet: CLUSTER_NAME-vnet
          zone: "3"